"use strict";
const $ = id => document.getElementById(id);
const names = {quality:"优化方案 · 低推理",fast:"快速方案 · 关闭推理",baseline:"原方案"};
const examples = ["请事假当天还有餐补吗？","电脑摔坏了需要赔偿吗？","晚上九点下班能报销打车吗？"];
let records = [], activeId = null, busy = false;
try { const stored = JSON.parse(localStorage.getItem("handbook-rag-history") || "[]"); if (Array.isArray(stored)) records = stored.filter(r => r && typeof r.question === "string" && Array.isArray(r.sources) && r.metrics && typeof r.answer === "string").slice(0,20); } catch (_) {}
function node(tag, text, cls) { const el=document.createElement(tag); if(text!==undefined) el.textContent=text; if(cls) el.className=cls; return el; }
function notice(message, loading=false) { $("notice").textContent=message; $("notice").hidden=!message; $("notice").classList.toggle("loading",loading); }
function persist() { try { localStorage.setItem("handbook-rag-history",JSON.stringify(records)); } catch (_) { notice("浏览器存储不可用或已满，本次记录仅在当前页面保留。"); } }
function history() { const target=$("history");target.replaceChildren();if(!records.length)target.append(node("p","还没有提问记录。","history-empty"));for(const r of records){const btn=node("button",r.question,"history-item"+(r.id===activeId?" active":""));btn.disabled=busy;btn.append(node("small",new Date(r.created).toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})));btn.addEventListener("click",()=>show(r));target.append(btn);} }
for(const question of examples){const btn=node("button",question,"example");btn.addEventListener("click",()=>{if(busy)return;$("question").value=question;counter();$("question").focus();});$("examples").append(btn);}
function counter() { $("counter").textContent=$("question").value.length+"/500"; }
$("question").addEventListener("input",counter);
$("question").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!busy)$("ask-form").requestSubmit();}});
function selectSource(id) { for(const el of document.querySelectorAll(".source")){el.classList.toggle("selected",el.dataset.sourceId===id);if(el.dataset.sourceId===id){el.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});el.focus({preventScroll:true});}}for(const el of document.querySelectorAll(".citation"))el.classList.toggle("active",el.dataset.sourceId===id); }
function inline(parent,text,sources){const pattern=/(〔[^〕]+〕|\*\*[^*]+\*\*)/g;let end=0;for(const match of text.matchAll(pattern)){parent.append(document.createTextNode(text.slice(end,match.index)));const token=match[0];if(token.startsWith("**")){parent.append(node("strong",token.slice(2,-2)));}else{const label=token.slice(1,-1);const source=sources.find(s=>s.label===label);if(source){const btn=node("button",label,"citation");btn.dataset.sourceId=source.id;btn.title="查看第"+source.pages.join("、")+"页原文";btn.addEventListener("click",()=>selectSource(source.id));parent.append(btn);}else{const span=node("span",token,"unmatched-citation");span.title="此标记未匹配实际输入来源，不能作为已核实引用";parent.append(span);}}end=match.index+token.length;}parent.append(document.createTextNode(text.slice(end)));}
function answerText(target,text,sources){for(const line of text.split("\n")){if(!line.trim()||/^[-—]{3,}$/.test(line.trim()))continue;const isHeading=/^#{1,4}\s/.test(line)||/^\*\*[^*]+\*\*[：:]?$/.test(line.trim());const clean=isHeading?line.replace(/^#{1,4}\s+/,"").replace(/^\*\*|\*\*([：:]?)$/g,""):line;const p=node(isHeading?"h3":"p");inline(p,clean,sources);target.append(p);}}
function evidence(sources){const target=$("sources");target.replaceChildren();if(!sources.length){target.append(node("p","暂无可展示的条款。","history-empty"));return;}for(const s of sources){const card=node("article",undefined,"source");card.tabIndex=-1;card.dataset.sourceId=s.id;const title=node("div",undefined,"source-title");title.append(node("span",s.label,"source-label"),node("span","第"+s.pages.join("、")+"页","source-page"));card.append(title,node("div",s.path||"无章节","source-path"));if(!s.in_context)card.append(node("p","检索命中，本方案未放入生成上下文。","not-in-context"));card.append(node("blockquote",s.text.length>200?s.text.slice(0,200)+"…":s.text));if(s.text.length>200){const detail=node("details");detail.append(node("summary","展开完整条款"),node("blockquote",s.text));card.append(detail);}target.append(card);}}
const seconds=v=>typeof v==="number"?v.toFixed(2)+"秒":"—";
function show(r){activeId=r.id;$("profile").value=r.profile;const target=$("conversation");target.replaceChildren(node("h2",r.question,"question-heading"),node("span",names[r.profile]||r.profile,"profile-tag"));if(r.answer){const answer=node("div",undefined,"answer");answerText(answer,r.answer,r.sources);target.append(answer);}else target.append(node("p",r.status==="retrieval_only"?"已找到以下条款。右侧可核对完整原文。":"本次没有完整回答，请查看下方提示和右侧证据。","history-empty"));evidence(r.sources);$("evidence-hint").textContent=r.status==="retrieval_only"?"检索命中条款，本次未调用模型。":"点击回答中的引用，核对原文。";const m=r.metrics;const metric=$("metrics");metric.hidden=false;metric.replaceChildren();for(const [label,value] of [["检索",seconds(m.retrieval_seconds)],["生成",seconds(m.generation_seconds)],["服务处理",seconds(m.total_seconds)],["浏览器等待",seconds(r.client_seconds)],["Tokens",m.total_tokens===null?"未知 / 未调用":String(m.total_tokens)],["请求尝试",String(m.attempts)]])metric.append(node("span",label+" "+value));if(r.usage&&r.usage.length){const details=node("details");details.append(node("summary","查看每次用量"));for(const u of r.usage){details.append(node("p",`第${u.attempt||1}次：输入 ${u.prompt_tokens??"未知"}，输出 ${u.completion_tokens??"未知"}；${u.error_type?"请求异常":u.finish_reason||"未知状态"}`));}metric.append(details);}notice(r.message||"");target.scrollTop=0;history();}
function setBusy(value){busy=value;for(const id of ["send","retrieve-button","profile","new-chat","clear-history"])$(id).disabled=value;$("question").disabled=value;for(const el of document.querySelectorAll(".example"))el.disabled=value;$("send").textContent=value?"正在回答…":"发送问题";history();}
async function ask(retrievalOnly){if(busy)return;const question=$("question").value.trim();if(!question){$("question").focus();notice("请先输入问题。");return;}const profile=$("profile").value;setBusy(true);$("conversation").replaceChildren(node("h2",question,"question-heading"),node("span",names[profile],"profile-tag"),node("p","正在查找相关条款，请稍候。","history-empty"));$("metrics").hidden=true;$("sources").replaceChildren(node("p","正在检索…","history-empty"));const start=performance.now();const ticker=setInterval(()=>notice(`正在${retrievalOnly?"检索条款":"检索并生成回答"}，已等待 ${Math.floor((performance.now()-start)/1000)} 秒。首次加载本地模型可能较慢。`,true),1000);notice("正在检索条款…",true);try{const response=await fetch("/api/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,profile,retrieval_only:retrievalOnly})});if(!response.ok){notice(response.status===409?"服务正在处理另一个问题，请稍后重试。":response.status===422?"问题格式无效，请输入1至500个字符。":"服务请求失败，请检查本地服务终端。");return;}const r=await response.json();r.client_seconds=(performance.now()-start)/1000;r.id=crypto.randomUUID();r.created=new Date().toISOString();records.unshift(r);records=records.slice(0,20);$("question").value="";counter();show(r);persist();}catch(_){notice("无法连接本地服务。请确认 python webapp.py 正在运行，再重试。");}finally{clearInterval(ticker);setBusy(false);}}
$("ask-form").addEventListener("submit",e=>{e.preventDefault();ask(false);});$("retrieve-button").addEventListener("click",()=>ask(true));
$("new-chat").addEventListener("click",()=>{activeId=null;$("conversation").replaceChildren(node("h2","新的问题","question-heading"),node("p","输入问题，或从左侧选择示例。","history-empty"));$("sources").replaceChildren(node("p","条款原文会显示在这里。","history-empty"));$("metrics").hidden=true;$("evidence-hint").textContent="点击回答中的引用，核对原文。";notice("");$("question").value="";counter();history();$("question").focus();});
$("clear-history").addEventListener("click",()=>{records=[];persist();$("new-chat").click();});
async function health(){try{const r=await fetch("/api/health");if(!r.ok)throw Error();const state=await r.json();$("health").textContent=state.busy?"正在处理问题":state.api_configured?"服务已连接":"服务已连接 · 仅检索可用";$("health").classList.add("ready");}catch(_){$("health").textContent="服务未连接";$("health").classList.remove("ready");}}
history();health();setInterval(health,15000);
